### ISSUE TITLE
Apollo Client config

### ISSUE THREAD

**Issue by Gillinghammer** [ryanbelke/strapi-next#1]
I've asked this all over the Strapi verse and cannot seem to figure out the answer. Docs are thin too concerning connecting to a deployed Strapi API.

My question is about your code here:
strapi-next/frontend/lib/apollo.js

I've since deployed my API to a server running Ubuntu... When I replace localhost:1337/graphql in this config file for Apollo my client cannot connect. I realize /graphql is not available for production, so I am wondering what I am missing to get my client connected to my hosted API? 

I feel like the answer should be this, but it won't work for me...
`const config = {
  link: new HttpLink({
    uri: 'http://myhostedAPI.coml',
    opts: {
      credentials: 'same-origin' 
    }
  })
};`

Thanks again for the great tutorial, works like a dream locally, just need to get a personal project online asap.

**Comment by Gillinghammer** [comment]
Got it all working simply by uploading both my API and client code to the same server/domain... Thanks

**Comment by ryanbelke** [comment]
@Gillinghammer In the Apollo config, the options object has the credential as 'same-origin', assuming your API/request come from the same domain. That's why you were able to get it working by putting it on the same domain, in a real world scenario you may want to segment these but for the POC they were assumed on the same origin for the sake of the demo. 
 The Apollo documentation on authentication may help here: https://www.apollographql.com/docs/react/recipes/authentication.html

**Comment by ryanbelke** [comment]
@Gillinghammer Had a chance to look at the Apollo config, to get it to work cross-domain just remove the opts object, it is not needed.

Sorry for the delay

```javascript
import { HttpLink } from "apollo-link-http";
import { withData } from "next-apollo";

const config = {
  link: new HttpLink({
    uri: "https://your-strapi-url.com/graphql", // Server URL (must be absolute)
  })
};
export default withData(config);
```
